language: node_js
node_js:
- v4
services: mongodb
deploy:
  provider: npm
  email: malykhinvi@gmail.com
  api_key:
    secure: lv60u9iJ4gJ5HSzqiXjB5lkTNje5/JhOtZuMhWBddYYUlSlqz9lbA6szxDJdtP3x2h4MuDJ2HGUOCsLsgseyr/lzu2Y3tm7jhWH/Np+jKMLK2ToGDikfW6X4gkajPNA97f8Y01w4X19qVQxgUbgQjvYXSfVpJjkkEFZosXWC/CfNQn8lpjj1xG7R6UEhUDl+ZjQ9tCci32rh8CqT7Ltl+pz76oYv6tHNpc+Yv8mCvv0gbT9qPWRlFQje1Y3OTzXF3CQeerOpAfAG7m3RupZH4QVbGNrdh5C6Fv4b3XZuSH11lm3MCsVZr6j1Kr/67uSapGy6Bjrf58mneguWj+qV4tofJAS9ctsa175H8SAy6Fz43S7YDTwF0w+08KdRszFXAqkK/O1SDdcPIspFk0RcHqtTY5gjaoqi777UhkCIYU5QfbaUGjRSBHoFxzeUzJogw+ABorZsf+zeKk68p13DUuXRQ87Z3MSr6MOTkxWsYKV7HcGdmwbHbcDkS2iJtLsQ2HdFdMBu9hLsfVeTsHSM+JIYFtavg7CeAJ1nPIafpPjW6geq9OWg4Fzh4XZmLYf5TY6vqYrQ2N3OtjipHYBSbOrUNonMsS4uOnGsyx1SepLuQg9Xug0Ykfh0YB8H9iBG1HDqnBiheYAyY+pFCTpxqgvlMmmPrRcMrAwqO+BuGjA=
  on:
    repo: malykhinvi/node-mongodb-changelog
